// 供應鏈資料模型：節點與公司關聯的初始種子資料，與 App 邏輯完全分離。
// 這份資料是「初始 seed」，之後可完全透過網站上的「編輯供應鏈」功能新增/修改/刪除，不會被覆蓋鎖死。
//
// 節點採「扁平陣列 + parentIds」設計，而非巢狀樹：
// - parentIds 可以有多個，代表同一個節點可以同時屬於多條供應鏈／多個上層分類（例如 CPO 同時歸在矽光子、光通訊、網通底下）
// - stage 只用來標示「這是什麼層級的分類」（theme 題材 / industry 產業 / upstream 上游 / midstream 中游 / downstream 下游 /
//   manufacturing 製造 / equipment 設備 / material 材料 / component 元件 / system 系統 / technology 技術 / ip IP），
//   不代表投資判斷或受惠程度
export const SUPPLY_CHAIN_NODES = [
  { id: 'ai', name: 'AI', parentIds: [], stage: 'theme' },
  { id: 'ai_compute', name: 'AI Compute', parentIds: ['ai'], stage: null },
  { id: 'ai_chip', name: 'AI Chip', parentIds: ['ai'], stage: null },
  { id: 'ai_accelerator', name: 'AI Accelerator', parentIds: ['ai', 'ai_chip', 'ic_design'], stage: null },
  { id: 'ai_server', name: 'AI Server', parentIds: ['ai', 'ai_infrastructure'], stage: 'system' },
  { id: 'ai_storage', name: 'AI Storage', parentIds: ['ai'], stage: null },
  { id: 'ai_networking', name: 'AI Networking', parentIds: ['ai'], stage: null },
  { id: 'ai_power', name: 'AI Power', parentIds: ['ai'], stage: null },
  { id: 'ai_cooling', name: 'AI Cooling', parentIds: ['ai'], stage: null },
  { id: 'ai_optical', name: 'AI Optical', parentIds: ['ai'], stage: null },
  { id: 'ai_advanced_packaging', name: 'AI Advanced Packaging', parentIds: ['ai'], stage: null },
  { id: 'ai_infrastructure', name: 'AI Infrastructure', parentIds: ['ai'], stage: null },
  { id: 'semiconductor', name: '半導體', parentIds: [], stage: 'industry' },
  { id: 'semiconductor_equipment', name: '半導體設備', parentIds: ['semiconductor'], stage: 'equipment' },
  { id: 'semiconductor_material', name: '半導體材料', parentIds: ['semiconductor'], stage: 'material' },
  { id: 'foundry', name: '晶圓代工', parentIds: ['semiconductor'], stage: 'manufacturing' },
  { id: 'idm', name: 'IDM', parentIds: ['semiconductor'], stage: null },
  { id: 'ic_design', name: 'IC設計', parentIds: ['semiconductor'], stage: 'upstream' },
  { id: 'asic', name: 'ASIC', parentIds: ['ic_design', 'semiconductor'], stage: null },
  { id: 'sip', name: 'SiP', parentIds: ['semiconductor'], stage: null },
  { id: 'advanced_packaging', name: '先進封裝', parentIds: ['ai_advanced_packaging', 'semiconductor'], stage: 'downstream' },
  { id: 'testing', name: 'IC測試', parentIds: ['semiconductor'], stage: 'downstream' },
  { id: 'osat', name: '封裝測試', parentIds: ['semiconductor'], stage: 'downstream' },
  { id: 'substrate', name: 'IC載板', parentIds: ['semiconductor'], stage: 'component' },
  { id: 'semiconductor_ip', name: '半導體IP', parentIds: ['semiconductor'], stage: 'ip' },
  { id: 'cpu', name: 'CPU', parentIds: ['ic_design'], stage: null },
  { id: 'gpu', name: 'GPU', parentIds: ['ai_accelerator', 'ic_design'], stage: null },
  { id: 'networking_asic', name: 'Networking ASIC', parentIds: ['ic_design'], stage: null },
  { id: 'switch_asic', name: 'Switch ASIC', parentIds: ['ic_design', 'networking'], stage: null },
  { id: 'phy', name: 'PHY', parentIds: ['ic_design'], stage: null },
  { id: 'serdes', name: 'SerDes', parentIds: ['ic_design'], stage: null },
  { id: 'power_ic', name: 'Power IC', parentIds: ['ic_design', 'power'], stage: null },
  { id: 'display_ic', name: 'Display IC', parentIds: ['ic_design'], stage: null },
  { id: 'memory_controller', name: 'Memory Controller', parentIds: ['ic_design'], stage: null },
  { id: 'rf_ic', name: 'RF IC', parentIds: ['ic_design'], stage: null },
  { id: 'advanced_node', name: '先進製程', parentIds: ['foundry'], stage: null },
  { id: 'mature_node', name: '成熟製程', parentIds: ['foundry'], stage: null },
  { id: 'specialty_process', name: '特殊製程', parentIds: ['foundry'], stage: null },
  { id: 'silicon_photonics_foundry', name: '矽光子晶圓製造', parentIds: ['foundry', 'silicon_photonics'], stage: null },
  { id: 'cowos', name: 'CoWoS', parentIds: ['advanced_packaging'], stage: null },
  { id: 'cowos_s', name: 'CoWoS-S', parentIds: ['advanced_packaging'], stage: null },
  { id: 'cowos_l', name: 'CoWoS-L', parentIds: ['advanced_packaging'], stage: null },
  { id: 'soic', name: 'SoIC', parentIds: ['advanced_packaging'], stage: null },
  { id: 'copos', name: 'CoPoS', parentIds: ['advanced_packaging'], stage: null },
  { id: 'cowop', name: 'CoWoP', parentIds: ['advanced_packaging'], stage: null },
  { id: 'foc', name: 'FoCoS', parentIds: ['advanced_packaging'], stage: null },
  { id: 'foplp', name: 'FOPLP', parentIds: ['advanced_packaging'], stage: null },
  { id: 'fan_out', name: 'Fan-Out', parentIds: ['advanced_packaging'], stage: null },
  { id: 'chiplet', name: 'Chiplet', parentIds: ['advanced_packaging'], stage: null },
  { id: 'hybrid_bonding', name: 'Hybrid Bonding', parentIds: ['advanced_packaging'], stage: null },
  { id: '2_5d_packaging', name: '2.5D封裝', parentIds: ['advanced_packaging'], stage: null },
  { id: '3d_packaging', name: '3D封裝', parentIds: ['advanced_packaging'], stage: null },
  { id: 'hbm_packaging', name: 'HBM封裝', parentIds: ['advanced_packaging'], stage: null },
  { id: 'npu', name: 'NPU', parentIds: ['ai_accelerator'], stage: null },
  { id: 'tpu', name: 'TPU', parentIds: ['ai_accelerator'], stage: null },
  { id: 'custom_ai_asic', name: 'Custom AI ASIC', parentIds: ['ai_accelerator'], stage: null },
  { id: 'inference_accelerator', name: 'Inference Accelerator', parentIds: ['ai_accelerator'], stage: null },
  { id: 'training_accelerator', name: 'Training Accelerator', parentIds: ['ai_accelerator'], stage: null },
  { id: 'server_odm', name: 'Server ODM', parentIds: ['ai_server'], stage: 'system' },
  { id: 'server_oem', name: 'Server OEM', parentIds: ['ai_server'], stage: null },
  { id: 'gpu_server', name: 'GPU Server', parentIds: ['ai_server'], stage: null },
  { id: 'ai_rack', name: 'AI Rack', parentIds: ['ai_server'], stage: null },
  { id: 'rack_integration', name: 'Rack Integration', parentIds: ['ai_server'], stage: null },
  { id: 'server_chassis', name: 'Server Chassis', parentIds: ['ai_server'], stage: null },
  { id: 'server_motherboard', name: 'Server Motherboard', parentIds: ['ai_server'], stage: null },
  { id: 'backplane', name: 'Backplane', parentIds: ['ai_server'], stage: null },
  { id: 'server_storage', name: 'Server Storage', parentIds: ['ai_server'], stage: null },
  { id: 'pcb', name: 'PCB', parentIds: ['ai_networking', 'ai_server'], stage: 'component' },
  { id: 'server_pcb', name: 'Server PCB', parentIds: ['pcb'], stage: null },
  { id: 'hdi', name: 'HDI', parentIds: ['pcb'], stage: null },
  { id: 'high_layer_pcb', name: '高層數PCB', parentIds: ['pcb'], stage: null },
  { id: 'high_speed_pcb', name: '高速PCB', parentIds: ['pcb'], stage: null },
  { id: 'backplane_pcb', name: 'Backplane PCB', parentIds: ['pcb'], stage: null },
  { id: 'networking_pcb', name: '網通PCB', parentIds: ['pcb'], stage: null },
  { id: 'automotive_pcb', name: '車用PCB', parentIds: ['automotive', 'pcb'], stage: null },
  { id: 'ccl', name: 'CCL / 高速材料', parentIds: ['pcb'], stage: 'material' },
  { id: 'high_speed_ccl', name: '高速CCL', parentIds: ['ccl'], stage: null },
  { id: 'low_loss_ccl', name: '低損耗CCL', parentIds: ['ccl'], stage: null },
  { id: 'very_low_loss_ccl', name: '極低損耗CCL', parentIds: ['ccl'], stage: null },
  { id: 'copper_foil', name: '銅箔', parentIds: ['ccl'], stage: null },
  { id: 'resin', name: '樹脂', parentIds: ['ccl'], stage: null },
  { id: 'glass_fiber', name: '玻纖布', parentIds: ['ccl'], stage: null },
  { id: 'abf', name: 'ABF載板', parentIds: ['substrate'], stage: null },
  { id: 'bt', name: 'BT載板', parentIds: ['substrate'], stage: null },
  { id: 'fc_bga', name: 'FC-BGA', parentIds: ['substrate'], stage: null },
  { id: 'fc_csp', name: 'FC-CSP', parentIds: ['substrate'], stage: null },
  { id: 'cooling', name: '散熱', parentIds: ['ai_cooling', 'ai_server'], stage: 'component' },
  { id: 'air_cooling', name: '氣冷', parentIds: ['cooling'], stage: null },
  { id: 'liquid_cooling', name: '液冷', parentIds: ['cooling'], stage: null },
  { id: 'cold_plate', name: 'Cold Plate', parentIds: ['cooling'], stage: null },
  { id: 'cooling_module', name: '散熱模組', parentIds: ['cooling'], stage: null },
  { id: 'heat_pipe', name: '熱導管', parentIds: ['cooling'], stage: null },
  { id: 'vapor_chamber', name: '均熱板', parentIds: ['cooling'], stage: null },
  { id: 'pump', name: '水泵', parentIds: ['cooling'], stage: null },
  { id: 'manifold', name: 'Manifold', parentIds: ['cooling'], stage: null },
  { id: 'power', name: 'AI / Data Center 電源', parentIds: ['ai_infrastructure', 'ai_power'], stage: 'component' },
  { id: 'power_supply', name: '電源供應器', parentIds: ['power'], stage: null },
  { id: 'server_psu', name: 'Server PSU', parentIds: ['power'], stage: null },
  { id: 'psu', name: 'PSU', parentIds: ['power'], stage: null },
  { id: 'power_management', name: '電源管理', parentIds: ['power'], stage: null },
  { id: 'power_module', name: 'Power Module', parentIds: ['power'], stage: null },
  { id: 'busbar', name: 'Busbar', parentIds: ['power'], stage: null },
  { id: 'pdu', name: 'PDU', parentIds: ['power'], stage: null },
  { id: 'ups', name: 'UPS', parentIds: ['power'], stage: null },
  { id: 'gan_power', name: 'GaN Power', parentIds: ['power'], stage: null },
  { id: 'sic_power', name: 'SiC Power', parentIds: ['power'], stage: null },
  { id: 'networking', name: '網通', parentIds: ['ai_networking'], stage: 'system' },
  { id: 'ethernet', name: 'Ethernet', parentIds: ['networking'], stage: null },
  { id: 'ethernet_switch', name: 'Ethernet Switch', parentIds: ['networking'], stage: null },
  { id: 'router', name: 'Router', parentIds: ['networking'], stage: null },
  { id: 'data_center_networking', name: 'Data Center Networking', parentIds: ['networking'], stage: null },
  { id: 'networking_equipment', name: 'Networking Equipment', parentIds: ['networking'], stage: null },
  { id: 'optical_networking', name: 'Optical Networking', parentIds: ['networking'], stage: null },
  { id: '400g', name: '400G', parentIds: ['networking'], stage: null },
  { id: '800g', name: '800G', parentIds: ['networking'], stage: null },
  { id: '1_6t', name: '1.6T', parentIds: ['networking'], stage: null },
  { id: 'optical_communication', name: '光通訊', parentIds: ['ai_optical', 'networking'], stage: 'industry' },
  { id: 'optical_component', name: '光學元件', parentIds: ['optical_communication'], stage: null },
  { id: 'laser', name: '雷射', parentIds: ['optical_communication'], stage: null },
  { id: 'laser_diode', name: '雷射二極體', parentIds: ['optical_communication'], stage: null },
  { id: 'eml', name: 'EML', parentIds: ['optical_communication'], stage: null },
  { id: 'cw_laser', name: 'CW Laser', parentIds: ['optical_communication'], stage: null },
  { id: 'inp', name: 'InP', parentIds: ['optical_communication'], stage: null },
  { id: 'gaas', name: 'GaAs', parentIds: ['optical_communication'], stage: null },
  { id: 'epitaxy', name: '磊晶', parentIds: ['optical_communication'], stage: null },
  { id: 'optical_transceiver', name: '光收發模組', parentIds: ['optical_communication'], stage: null },
  { id: 'optical_module', name: '光模組', parentIds: ['optical_communication'], stage: null },
  { id: 'fiber', name: '光纖', parentIds: ['optical_communication'], stage: null },
  { id: 'fiber_connector', name: '光纖連接器', parentIds: ['optical_communication'], stage: null },
  { id: 'fiber_array', name: 'FAU', parentIds: ['optical_communication'], stage: null },
  { id: 'optical_coupling', name: '光耦合', parentIds: ['optical_communication'], stage: null },
  { id: 'silicon_photonics', name: '矽光子', parentIds: ['ai_optical', 'optical_communication'], stage: 'technology' },
  { id: 'cpo', name: 'CPO', parentIds: ['networking', 'optical_communication', 'silicon_photonics'], stage: 'technology' },
  { id: 'optical_engine', name: 'Optical Engine', parentIds: ['silicon_photonics'], stage: null },
  { id: 'external_laser', name: 'External Laser', parentIds: ['silicon_photonics'], stage: null },
  { id: 'fau', name: 'Fiber Array Unit', parentIds: ['silicon_photonics'], stage: null },
  { id: 'fiber_coupling', name: '光纖耦合', parentIds: ['silicon_photonics'], stage: null },
  { id: 'optical_alignment', name: '光學對位', parentIds: ['silicon_photonics'], stage: null },
  { id: 'photonic_package', name: '光電封裝', parentIds: ['silicon_photonics'], stage: null },
  { id: 'cpo_laser', name: 'CPO Laser', parentIds: ['cpo'], stage: null },
  { id: 'cpo_fau', name: 'CPO FAU', parentIds: ['cpo'], stage: null },
  { id: 'cpo_coupling', name: 'CPO Coupling', parentIds: ['cpo'], stage: null },
  { id: 'cpo_package', name: 'CPO Packaging', parentIds: ['cpo'], stage: null },
  { id: 'cpo_optical_engine', name: 'CPO Optical Engine', parentIds: ['cpo'], stage: null },
  { id: 'cpo_switch', name: 'CPO Switch', parentIds: ['cpo'], stage: null },
  { id: 'memory', name: '記憶體', parentIds: ['ai_storage', 'semiconductor'], stage: 'industry' },
  { id: 'dram', name: 'DRAM', parentIds: ['memory'], stage: null },
  { id: 'nand', name: 'NAND', parentIds: ['memory'], stage: null },
  { id: 'hbm', name: 'HBM', parentIds: ['memory'], stage: null },
  { id: 'hbm3', name: 'HBM3', parentIds: ['memory'], stage: null },
  { id: 'hbm3e', name: 'HBM3E', parentIds: ['memory'], stage: null },
  { id: 'hbm4', name: 'HBM4', parentIds: ['memory'], stage: null },
  { id: 'memory_module', name: '記憶體模組', parentIds: ['memory'], stage: null },
  { id: 'ssd', name: 'SSD', parentIds: ['memory', 'storage'], stage: null },
  { id: 'enterprise_ssd', name: 'Enterprise SSD', parentIds: ['memory', 'storage'], stage: null },
  { id: 'consumer_ssd', name: 'Consumer SSD', parentIds: ['memory'], stage: null },
  { id: 'nand_flash', name: 'NAND Flash', parentIds: ['memory'], stage: null },
  { id: 'storage', name: '儲存', parentIds: ['ai_storage'], stage: 'system' },
  { id: 'nvme', name: 'NVMe', parentIds: ['storage'], stage: null },
  { id: 'storage_controller', name: 'Storage Controller', parentIds: ['storage'], stage: null },
  { id: 'storage_module', name: 'Storage Module', parentIds: ['storage'], stage: null },
  { id: 'data_center_storage', name: 'Data Center Storage', parentIds: ['storage'], stage: null },
  { id: 'wafer_cleaning', name: '晶圓清洗', parentIds: ['semiconductor_equipment'], stage: null },
  { id: 'etch', name: '蝕刻', parentIds: ['semiconductor_equipment'], stage: null },
  { id: 'deposition', name: '薄膜沉積', parentIds: ['semiconductor_equipment'], stage: null },
  { id: 'lithography', name: '曝光', parentIds: ['semiconductor_equipment'], stage: null },
  { id: 'inspection', name: '檢測', parentIds: ['semiconductor_equipment'], stage: null },
  { id: 'metrology', name: '量測', parentIds: ['semiconductor_equipment'], stage: null },
  { id: 'packaging_equipment', name: '封裝設備', parentIds: ['semiconductor_equipment'], stage: null },
  { id: 'testing_equipment', name: '測試設備', parentIds: ['semiconductor_equipment'], stage: null },
  { id: 'advanced_packaging_equipment', name: '先進封裝設備', parentIds: ['semiconductor_equipment'], stage: null },
  { id: 'silicon_wafer', name: '矽晶圓', parentIds: ['semiconductor_material'], stage: null },
  { id: 'photoresist', name: '光阻', parentIds: ['semiconductor_material'], stage: null },
  { id: 'chemical', name: '電子化學品', parentIds: ['semiconductor_material'], stage: null },
  { id: 'specialty_gas', name: '特殊氣體', parentIds: ['semiconductor_material'], stage: null },
  { id: 'cmp_material', name: 'CMP材料', parentIds: ['semiconductor_material'], stage: null },
  { id: 'target', name: '靶材', parentIds: ['semiconductor_material'], stage: null },
  { id: 'photo_mask', name: '光罩', parentIds: ['semiconductor_material'], stage: null },
  { id: 'packaging_material', name: '封裝材料', parentIds: ['semiconductor_material'], stage: null },
  { id: 'wafer_test', name: '晶圓測試', parentIds: ['testing'], stage: null },
  { id: 'final_test', name: '成品測試', parentIds: ['testing'], stage: null },
  { id: 'system_level_test', name: 'System Level Test', parentIds: ['testing'], stage: null },
  { id: 'ai_chip_test', name: 'AI Chip Test', parentIds: ['testing'], stage: null },
  { id: 'memory_test', name: 'Memory Test', parentIds: ['testing'], stage: null },
  { id: 'automotive', name: '車用電子', parentIds: [], stage: 'industry' },
  { id: 'automotive_semiconductor', name: '車用半導體', parentIds: ['automotive'], stage: null },
  { id: 'adas', name: 'ADAS', parentIds: ['automotive'], stage: null },
  { id: 'ev', name: 'EV', parentIds: ['automotive'], stage: null },
  { id: 'automotive_power', name: '車用電源', parentIds: ['automotive'], stage: null },
  { id: 'automotive_sensor', name: '車用感測器', parentIds: ['automotive'], stage: null },
  { id: 'robotics', name: '機器人', parentIds: [], stage: 'theme' },
  { id: 'industrial_robot', name: '工業機器人', parentIds: ['robotics'], stage: null },
  { id: 'humanoid_robot', name: '人形機器人', parentIds: ['robotics'], stage: null },
  { id: 'robot_controller', name: '機器人控制器', parentIds: ['robotics'], stage: null },
  { id: 'robot_motor', name: '機器人馬達', parentIds: ['robotics'], stage: null },
  { id: 'robot_reducer', name: '減速機', parentIds: ['robotics'], stage: null },
  { id: 'robot_sensor', name: '機器人感測器', parentIds: ['robotics'], stage: null },
  { id: 'robot_vision', name: '機器人視覺', parentIds: ['robotics'], stage: null },
  { id: 'power_infrastructure', name: '電力基礎建設', parentIds: [], stage: 'industry' },
  { id: 'transformer', name: '變壓器', parentIds: ['power_infrastructure'], stage: null },
  { id: 'switchgear', name: '開關設備', parentIds: ['power_infrastructure'], stage: null },
  { id: 'power_distribution', name: '配電', parentIds: ['power_infrastructure'], stage: null },
  { id: 'grid', name: '電網', parentIds: ['power_infrastructure'], stage: null },
  { id: 'data_center_power', name: '資料中心電力', parentIds: ['power_infrastructure'], stage: null },
  { id: 'energy_storage', name: '儲能', parentIds: ['power_infrastructure'], stage: null },
  { id: 'server', name: '伺服器', parentIds: ['ai_server'], stage: null },
];

// 公司 ↔ 供應鏈節點 多對多關聯。
// role 只描述公司在該節點的客觀角色（製造/設計/封裝/測試/材料/設備/系統整合/模組/元件/平台等），
// 不包含受惠程度、目標價、買賣建議等主觀投資判斷。
// 這份資料僅描述公司「目前公開揭露的產業位置」，並非推薦股票，且會隨客戶/產品/產能/技術變化而需要更新，
// 請透過「編輯供應鏈」功能維護，不要視為永久不變的事實。
export const COMPANY_LINKS = [
  { symbol: '2330', name: '台積電', nodeId: 'foundry', role: '全球先進晶圓代工' },
  { symbol: '2330', name: '台積電', nodeId: 'advanced_node', role: 'AI/HPC先進製程' },
  { symbol: '2330', name: '台積電', nodeId: 'advanced_packaging', role: '先進封裝平台' },
  { symbol: '2330', name: '台積電', nodeId: 'cowos', role: 'CoWoS' },
  { symbol: '2330', name: '台積電', nodeId: 'soic', role: 'SoIC' },
  { symbol: '2330', name: '台積電', nodeId: 'silicon_photonics', role: '矽光子先進封裝平台' },
  { symbol: '2330', name: '台積電', nodeId: 'cpo', role: 'CPO相關封裝' },
  { symbol: '2330', name: '台積電', nodeId: 'asic', role: 'ASIC製造' },
  { symbol: '2303', name: '聯電', nodeId: 'foundry', role: '晶圓代工' },
  { symbol: '2303', name: '聯電', nodeId: 'mature_node', role: '成熟製程' },
  { symbol: '2303', name: '聯電', nodeId: 'specialty_process', role: '特殊製程' },
  { symbol: '2303', name: '聯電', nodeId: 'silicon_photonics', role: '部分光電/矽光子相關布局' },
  { symbol: '3661', name: '世芯-KY', nodeId: 'ic_design', role: 'ASIC設計服務' },
  { symbol: '3661', name: '世芯-KY', nodeId: 'asic', role: 'HPC / AI ASIC' },
  { symbol: '3661', name: '世芯-KY', nodeId: 'custom_ai_asic', role: '客製化晶片設計' },
  { symbol: '3661', name: '世芯-KY', nodeId: 'ai_accelerator', role: '客製化晶片設計' },
  { symbol: '3443', name: '創意', nodeId: 'ic_design', role: 'ASIC設計服務' },
  { symbol: '3443', name: '創意', nodeId: 'asic', role: 'SoC/IP' },
  { symbol: '3443', name: '創意', nodeId: 'custom_ai_asic', role: 'HPC/AI客製化晶片' },
  { symbol: '3443', name: '創意', nodeId: 'semiconductor_ip', role: 'SoC/IP' },
  { symbol: '3035', name: '智原', nodeId: 'ic_design', role: 'ASIC' },
  { symbol: '3035', name: '智原', nodeId: 'asic', role: 'SoC' },
  { symbol: '3035', name: '智原', nodeId: 'semiconductor_ip', role: 'IP' },
  { symbol: '3035', name: '智原', nodeId: 'networking_asic', role: '客製化晶片' },
  { symbol: '5274', name: '信驊', nodeId: 'ic_design', role: 'BMC' },
  { symbol: '5274', name: '信驊', nodeId: 'server', role: '伺服器管理晶片' },
  { symbol: '5274', name: '信驊', nodeId: 'ai_server', role: 'AI Server管理平台' },
  { symbol: '6533', name: '晶心科', nodeId: 'ic_design', role: 'RISC-V CPU IP' },
  { symbol: '6533', name: '晶心科', nodeId: 'semiconductor_ip', role: '半導體IP' },
  { symbol: '2454', name: '聯發科', nodeId: 'ic_design', role: 'SoC' },
  { symbol: '2454', name: '聯發科', nodeId: 'ai_accelerator', role: 'AI' },
  { symbol: '2454', name: '聯發科', nodeId: 'networking_asic', role: '網通/邊緣運算' },
  { symbol: '2454', name: '聯發科', nodeId: 'cpu', role: 'CPU' },
  { symbol: '3711', name: '日月光投控', nodeId: 'osat', role: '封裝測試' },
  { symbol: '3711', name: '日月光投控', nodeId: 'advanced_packaging', role: '先進封裝' },
  { symbol: '3711', name: '日月光投控', nodeId: '2_5d_packaging', role: '2.5D/異質整合' },
  { symbol: '3711', name: '日月光投控', nodeId: 'fan_out', role: '先進封裝' },
  { symbol: '3711', name: '日月光投控', nodeId: 'cpo', role: '矽光子/CPO相關封裝' },
  { symbol: '3711', name: '日月光投控', nodeId: 'silicon_photonics', role: '矽光子/CPO相關封裝' },
  { symbol: '3711', name: '日月光投控', nodeId: 'testing', role: '封裝測試' },
  { symbol: '6239', name: '力成', nodeId: 'osat', role: '記憶體封測' },
  { symbol: '6239', name: '力成', nodeId: 'advanced_packaging', role: '先進封裝' },
  { symbol: '6239', name: '力成', nodeId: 'foplp', role: 'FOPLP' },
  { symbol: '6239', name: '力成', nodeId: 'memory', role: 'AI/HPC封裝' },
  { symbol: '6239', name: '力成', nodeId: 'testing', role: '封裝測試' },
  { symbol: '6239', name: '力成', nodeId: 'memory_test', role: 'AI/HPC封裝' },
  { symbol: '2449', name: '京元電子', nodeId: 'testing', role: '晶圓測試' },
  { symbol: '2449', name: '京元電子', nodeId: 'wafer_test', role: '晶圓測試' },
  { symbol: '2449', name: '京元電子', nodeId: 'final_test', role: '成品測試' },
  { symbol: '2449', name: '京元電子', nodeId: 'ai_chip_test', role: '高階IC測試' },
  { symbol: '3037', name: '欣興', nodeId: 'substrate', role: 'ABF載板' },
  { symbol: '3037', name: '欣興', nodeId: 'abf', role: 'ABF載板' },
  { symbol: '3037', name: '欣興', nodeId: 'fc_bga', role: 'FC-BGA' },
  { symbol: '3037', name: '欣興', nodeId: 'pcb', role: 'PCB' },
  { symbol: '3037', name: '欣興', nodeId: 'advanced_packaging', role: 'IC載板' },
  { symbol: '3037', name: '欣興', nodeId: 'high_speed_pcb', role: '高階PCB' },
  { symbol: '3037', name: '欣興', nodeId: 'server_pcb', role: 'AI Server PCB' },
  { symbol: '8046', name: '南電', nodeId: 'substrate', role: 'ABF載板' },
  { symbol: '8046', name: '南電', nodeId: 'abf', role: 'ABF載板' },
  { symbol: '8046', name: '南電', nodeId: 'fc_bga', role: 'FC-BGA' },
  { symbol: '3189', name: '景碩', nodeId: 'substrate', role: 'IC載板' },
  { symbol: '3189', name: '景碩', nodeId: 'abf', role: 'ABF載板' },
  { symbol: '3189', name: '景碩', nodeId: 'fc_bga', role: 'FC-BGA' },
  { symbol: '2317', name: '鴻海', nodeId: 'ai_server', role: 'AI Server' },
  { symbol: '2317', name: '鴻海', nodeId: 'server_odm', role: '系統整合' },
  { symbol: '2317', name: '鴻海', nodeId: 'server_oem', role: '系統整合' },
  { symbol: '2317', name: '鴻海', nodeId: 'ai_rack', role: 'AI機櫃' },
  { symbol: '2317', name: '鴻海', nodeId: 'networking', role: '網通設備' },
  { symbol: '2317', name: '鴻海', nodeId: 'cpo', role: 'CPO相關系統' },
  { symbol: '2317', name: '鴻海', nodeId: 'networking_equipment', role: '網通設備' },
  { symbol: '2382', name: '廣達', nodeId: 'ai_server', role: 'AI Server ODM' },
  { symbol: '2382', name: '廣達', nodeId: 'server_odm', role: 'AI Server ODM' },
  { symbol: '2382', name: '廣達', nodeId: 'gpu_server', role: 'GPU Server' },
  { symbol: '2382', name: '廣達', nodeId: 'ai_rack', role: 'AI Rack' },
  { symbol: '3231', name: '緯創', nodeId: 'ai_server', role: 'AI Server' },
  { symbol: '3231', name: '緯創', nodeId: 'server_odm', role: 'AI Server' },
  { symbol: '3231', name: '緯創', nodeId: 'gpu_server', role: 'GPU Server' },
  { symbol: '3231', name: '緯創', nodeId: 'ai_rack', role: 'AI Rack' },
  { symbol: '6669', name: '緯穎', nodeId: 'ai_server', role: 'Cloud/AI Server' },
  { symbol: '6669', name: '緯穎', nodeId: 'server_odm', role: 'Cloud Server' },
  { symbol: '6669', name: '緯穎', nodeId: 'gpu_server', role: 'AI Server' },
  { symbol: '6669', name: '緯穎', nodeId: 'data_center_networking', role: 'Data Center' },
  { symbol: '6669', name: '緯穎', nodeId: 'networking', role: 'Data Center' },
  { symbol: '2376', name: '技嘉', nodeId: 'ai_server', role: 'GPU Server' },
  { symbol: '2376', name: '技嘉', nodeId: 'gpu_server', role: 'GPU Server' },
  { symbol: '2376', name: '技嘉', nodeId: 'server_motherboard', role: 'Server Motherboard' },
  { symbol: '2376', name: '技嘉', nodeId: 'ai_rack', role: 'AI Rack' },
  { symbol: '2356', name: '英業達', nodeId: 'ai_server', role: 'AI Server' },
  { symbol: '2356', name: '英業達', nodeId: 'server_odm', role: 'Server ODM' },
  { symbol: '2356', name: '英業達', nodeId: 'gpu_server', role: 'GPU Server' },
  { symbol: '2324', name: '仁寶', nodeId: 'ai_server', role: '系統整合' },
  { symbol: '2324', name: '仁寶', nodeId: 'server_odm', role: 'Server ODM' },
  { symbol: '2313', name: '華通', nodeId: 'pcb', role: 'HDI' },
  { symbol: '2313', name: '華通', nodeId: 'hdi', role: 'HDI' },
  { symbol: '2313', name: '華通', nodeId: 'high_layer_pcb', role: '高階PCB' },
  { symbol: '2313', name: '華通', nodeId: 'server_pcb', role: 'Server PCB' },
  { symbol: '2368', name: '金像電', nodeId: 'pcb', role: '高階PCB' },
  { symbol: '2368', name: '金像電', nodeId: 'high_layer_pcb', role: '高階PCB' },
  { symbol: '2368', name: '金像電', nodeId: 'high_speed_pcb', role: '高速PCB' },
  { symbol: '2368', name: '金像電', nodeId: 'server_pcb', role: 'AI Server PCB' },
  { symbol: '4927', name: '泰鼎-KY', nodeId: 'pcb', role: 'PCB' },
  { symbol: '4927', name: '泰鼎-KY', nodeId: 'automotive_pcb', role: '車用PCB' },
  { symbol: '4927', name: '泰鼎-KY', nodeId: 'hdi', role: 'HDI' },
  { symbol: '3044', name: '健鼎', nodeId: 'pcb', role: '高階PCB' },
  { symbol: '3044', name: '健鼎', nodeId: 'high_layer_pcb', role: '高階PCB' },
  { symbol: '3044', name: '健鼎', nodeId: 'server_pcb', role: 'Server PCB' },
  { symbol: '3044', name: '健鼎', nodeId: 'networking_pcb', role: '網通PCB' },
  { symbol: '2383', name: '台光電', nodeId: 'ccl', role: '高速CCL' },
  { symbol: '2383', name: '台光電', nodeId: 'high_speed_ccl', role: '高速CCL' },
  { symbol: '2383', name: '台光電', nodeId: 'low_loss_ccl', role: '低損耗材料' },
  { symbol: '2383', name: '台光電', nodeId: 'very_low_loss_ccl', role: '高頻高速材料' },
  { symbol: '6274', name: '台燿', nodeId: 'ccl', role: '高速CCL' },
  { symbol: '6274', name: '台燿', nodeId: 'high_speed_ccl', role: '高速CCL' },
  { symbol: '6274', name: '台燿', nodeId: 'low_loss_ccl', role: '高頻高速材料' },
  { symbol: '6213', name: '聯茂', nodeId: 'ccl', role: 'CCL' },
  { symbol: '6213', name: '聯茂', nodeId: 'high_speed_ccl', role: '高速材料' },
  { symbol: '6213', name: '聯茂', nodeId: 'low_loss_ccl', role: '高速材料' },
  { symbol: '3324', name: '雙鴻', nodeId: 'cooling', role: '散熱模組' },
  { symbol: '3324', name: '雙鴻', nodeId: 'liquid_cooling', role: '液冷' },
  { symbol: '3324', name: '雙鴻', nodeId: 'cold_plate', role: 'Cold Plate' },
  { symbol: '3324', name: '雙鴻', nodeId: 'heat_pipe', role: '均熱板' },
  { symbol: '3324', name: '雙鴻', nodeId: 'vapor_chamber', role: '均熱板' },
  { symbol: '3017', name: '奇鋐', nodeId: 'cooling', role: 'AI Server散熱' },
  { symbol: '3017', name: '奇鋐', nodeId: 'liquid_cooling', role: '液冷' },
  { symbol: '3017', name: '奇鋐', nodeId: 'cold_plate', role: 'Cold Plate' },
  { symbol: '6230', name: '超眾', nodeId: 'cooling', role: '散熱模組' },
  { symbol: '6230', name: '超眾', nodeId: 'heat_pipe', role: '熱導管' },
  { symbol: '6230', name: '超眾', nodeId: 'vapor_chamber', role: '均熱板' },
  { symbol: '2308', name: '台達電', nodeId: 'power', role: 'Server PSU' },
  { symbol: '2308', name: '台達電', nodeId: 'server_psu', role: 'Server PSU' },
  { symbol: '2308', name: '台達電', nodeId: 'power_supply', role: '電源管理' },
  { symbol: '2308', name: '台達電', nodeId: 'data_center_power', role: 'Data Center電力' },
  { symbol: '2308', name: '台達電', nodeId: 'power_infrastructure', role: 'AI電源' },
  { symbol: '2308', name: '台達電', nodeId: 'networking', role: '網通' },
  { symbol: '2308', name: '台達電', nodeId: 'cpo', role: 'CPO相關設備' },
  { symbol: '2301', name: '光寶科', nodeId: 'power', role: '電源供應器' },
  { symbol: '2301', name: '光寶科', nodeId: 'server_psu', role: 'Server Power' },
  { symbol: '2301', name: '光寶科', nodeId: 'power_supply', role: '電源供應器' },
  { symbol: '2301', name: '光寶科', nodeId: 'ai_server', role: 'AI Server' },
  { symbol: '6282', name: '康舒', nodeId: 'power', role: '電源供應器' },
  { symbol: '6282', name: '康舒', nodeId: 'power_supply', role: '電源供應器' },
  { symbol: '6282', name: '康舒', nodeId: 'server_psu', role: 'Server PSU' },
  { symbol: '3081', name: '聯亞', nodeId: 'optical_communication', role: '光通訊雷射' },
  { symbol: '3081', name: '聯亞', nodeId: 'laser', role: 'InP磊晶' },
  { symbol: '3081', name: '聯亞', nodeId: 'eml', role: 'EML' },
  { symbol: '3081', name: '聯亞', nodeId: 'cw_laser', role: 'CW Laser' },
  { symbol: '3081', name: '聯亞', nodeId: 'inp', role: 'InP磊晶' },
  { symbol: '3081', name: '聯亞', nodeId: 'epitaxy', role: 'InP磊晶' },
  { symbol: '2455', name: '全新', nodeId: 'optical_communication', role: '光通訊元件' },
  { symbol: '2455', name: '全新', nodeId: 'laser', role: '雷射' },
  { symbol: '2455', name: '全新', nodeId: 'gaas', role: 'GaAs磊晶' },
  { symbol: '2455', name: '全新', nodeId: 'inp', role: 'InP磊晶' },
  { symbol: '2455', name: '全新', nodeId: 'epitaxy', role: 'GaAs/InP磊晶' },
  { symbol: '4991', name: '環宇-KY', nodeId: 'optical_communication', role: '光電磊晶' },
  { symbol: '4991', name: '環宇-KY', nodeId: 'epitaxy', role: '光電磊晶' },
  { symbol: '4991', name: '環宇-KY', nodeId: 'gaas', role: 'GaAs' },
  { symbol: '4991', name: '環宇-KY', nodeId: 'inp', role: 'InP' },
  { symbol: '4979', name: '華星光', nodeId: 'optical_communication', role: '光通訊模組' },
  { symbol: '4979', name: '華星光', nodeId: 'optical_transceiver', role: '光收發模組' },
  { symbol: '4979', name: '華星光', nodeId: 'optical_module', role: '光通訊模組' },
  { symbol: '4979', name: '華星光', nodeId: 'laser', role: '光電元件' },
  { symbol: '6442', name: '光聖', nodeId: 'optical_communication', role: '光纖連接' },
  { symbol: '6442', name: '光聖', nodeId: 'optical_component', role: '光學元件' },
  { symbol: '6442', name: '光聖', nodeId: 'fiber_connector', role: '光纖連接' },
  { symbol: '6442', name: '光聖', nodeId: 'optical_module', role: '光通訊模組' },
  { symbol: '3163', name: '波若威', nodeId: 'optical_communication', role: '光被動元件' },
  { symbol: '3163', name: '波若威', nodeId: 'optical_component', role: '光被動元件' },
  { symbol: '3163', name: '波若威', nodeId: 'fiber', role: '光纖' },
  { symbol: '3163', name: '波若威', nodeId: 'fiber_connector', role: '光通訊' },
  { symbol: '3163', name: '波若威', nodeId: 'silicon_photonics', role: '矽光子相關供應鏈' },
  { symbol: '3363', name: '上詮', nodeId: 'optical_communication', role: 'FAU' },
  { symbol: '3363', name: '上詮', nodeId: 'silicon_photonics', role: 'FAU' },
  { symbol: '3363', name: '上詮', nodeId: 'cpo', role: 'CPO' },
  { symbol: '3363', name: '上詮', nodeId: 'fau', role: 'FAU' },
  { symbol: '3363', name: '上詮', nodeId: 'fiber_coupling', role: '光纖耦合' },
  { symbol: '3363', name: '上詮', nodeId: 'optical_alignment', role: '光學對位' },
  { symbol: '6451', name: '訊芯-KY', nodeId: 'optical_communication', role: '光電封裝' },
  { symbol: '6451', name: '訊芯-KY', nodeId: 'silicon_photonics', role: 'SiP/矽光子封裝' },
  { symbol: '6451', name: '訊芯-KY', nodeId: 'cpo', role: 'CPO' },
  { symbol: '6451', name: '訊芯-KY', nodeId: 'photonic_package', role: '光電封裝' },
  { symbol: '6451', name: '訊芯-KY', nodeId: 'advanced_packaging', role: 'SiP' },
  { symbol: '4977', name: '眾達-KY', nodeId: 'optical_communication', role: '光模組' },
  { symbol: '4977', name: '眾達-KY', nodeId: 'optical_module', role: '光模組' },
  { symbol: '4977', name: '眾達-KY', nodeId: 'external_laser', role: '外部雷射相關模組' },
  { symbol: '4977', name: '眾達-KY', nodeId: 'cpo', role: 'CPO' },
  { symbol: '3450', name: '聯鈞', nodeId: 'optical_communication', role: '光模組' },
  { symbol: '3450', name: '聯鈞', nodeId: 'optical_module', role: '光模組' },
  { symbol: '3450', name: '聯鈞', nodeId: 'laser', role: '雷射相關' },
  { symbol: '3450', name: '聯鈞', nodeId: 'cpo', role: 'CPO' },
  { symbol: '4908', name: '前鼎', nodeId: 'optical_communication', role: '光收發模組' },
  { symbol: '4908', name: '前鼎', nodeId: 'optical_module', role: '光收發模組' },
  { symbol: '4908', name: '前鼎', nodeId: 'optical_transceiver', role: '光收發模組' },
  { symbol: '2345', name: '智邦', nodeId: 'networking', role: 'Ethernet Switch' },
  { symbol: '2345', name: '智邦', nodeId: 'ethernet_switch', role: 'Ethernet Switch' },
  { symbol: '2345', name: '智邦', nodeId: 'data_center_networking', role: 'Data Center Networking' },
  { symbol: '2345', name: '智邦', nodeId: 'optical_networking', role: 'AI Networking' },
  { symbol: '2345', name: '智邦', nodeId: 'cpo', role: 'CPO相關交換器' },
  { symbol: '2408', name: '南亞科', nodeId: 'memory', role: 'DRAM' },
  { symbol: '2408', name: '南亞科', nodeId: 'dram', role: 'DRAM' },
  { symbol: '2344', name: '華邦電', nodeId: 'memory', role: 'DRAM/NAND' },
  { symbol: '2344', name: '華邦電', nodeId: 'dram', role: 'DRAM' },
  { symbol: '2344', name: '華邦電', nodeId: 'nand', role: 'NAND/Specialty Memory' },
  { symbol: '8299', name: '群聯', nodeId: 'memory', role: 'NAND控制器' },
  { symbol: '8299', name: '群聯', nodeId: 'nand', role: 'NAND控制器' },
  { symbol: '8299', name: '群聯', nodeId: 'ssd', role: 'SSD/儲存解決方案' },
  { symbol: '8299', name: '群聯', nodeId: 'storage_controller', role: 'SSD/儲存解決方案' },
  { symbol: '3260', name: '威剛', nodeId: 'memory', role: '記憶體模組' },
  { symbol: '3260', name: '威剛', nodeId: 'memory_module', role: '記憶體模組' },
  { symbol: '3260', name: '威剛', nodeId: 'ssd', role: 'SSD' },
  { symbol: '4967', name: '十銓', nodeId: 'memory', role: '記憶體模組' },
  { symbol: '4967', name: '十銓', nodeId: 'memory_module', role: '記憶體模組' },
  { symbol: '4967', name: '十銓', nodeId: 'ssd', role: 'SSD' },
  { symbol: '6415', name: '矽力*-KY', nodeId: 'power_ic', role: '電源管理IC/PMIC' },
  { symbol: '6415', name: '矽力*-KY', nodeId: 'power_management', role: '電源管理IC/PMIC' },
  { symbol: '3016', name: '嘉晶', nodeId: 'semiconductor_material', role: '半導體材料' },
  { symbol: '3016', name: '嘉晶', nodeId: 'silicon_wafer', role: '半導體材料' },
  { symbol: '3016', name: '嘉晶', nodeId: 'power_ic', role: '功率半導體相關' },
  { symbol: '3016', name: '嘉晶', nodeId: 'sic_power', role: '功率半導體相關' },
  { symbol: '2049', name: '上銀', nodeId: 'robotics', role: '工業自動化/精密傳動' },
  { symbol: '2049', name: '上銀', nodeId: 'industrial_robot', role: '工業自動化/精密傳動/機器人零組件' },
  { symbol: '1590', name: '亞德客-KY', nodeId: 'robotics', role: '氣動元件/自動化' },
  { symbol: '1590', name: '亞德客-KY', nodeId: 'industrial_robot', role: '氣動元件/自動化' },
  { symbol: '1504', name: '東元', nodeId: 'robotics', role: '馬達/自動化' },
  { symbol: '1504', name: '東元', nodeId: 'robot_motor', role: '馬達' },
  { symbol: '1504', name: '東元', nodeId: 'industrial_robot', role: '工業機器人' },
  { symbol: '1503', name: '士電', nodeId: 'power_infrastructure', role: '變壓器/配電設備' },
  { symbol: '1503', name: '士電', nodeId: 'transformer', role: '變壓器' },
  { symbol: '1503', name: '士電', nodeId: 'switchgear', role: '配電設備' },
  { symbol: '1503', name: '士電', nodeId: 'power_distribution', role: '配電設備' },
  { symbol: '1503', name: '士電', nodeId: 'data_center_power', role: '電力基礎建設' },
  { symbol: '1513', name: '中興電', nodeId: 'power_infrastructure', role: '電力設備' },
  { symbol: '1513', name: '中興電', nodeId: 'transformer', role: '變壓器' },
  { symbol: '1513', name: '中興電', nodeId: 'switchgear', role: '配電' },
  { symbol: '1513', name: '中興電', nodeId: 'power_distribution', role: '配電' },
  { symbol: '1513', name: '中興電', nodeId: 'grid', role: '電力設備' },
  { symbol: '1519', name: '華城', nodeId: 'power_infrastructure', role: '變壓器' },
  { symbol: '1519', name: '華城', nodeId: 'transformer', role: '變壓器' },
  { symbol: '1519', name: '華城', nodeId: 'grid', role: '電網' },
  { symbol: '1519', name: '華城', nodeId: 'data_center_power', role: '資料中心電力' },
];
